# Generated by Django 5.1.4 on 2025-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data_limit',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
