# Generated by Django 4.2.17 on 2025-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_usersubscription_data_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='data_type',
            field=models.CharField(choices=[('GB', 'GB'), ('MB', 'MB')], default='MB', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('Month', 'Month'), ('Day', 'Day'), ('Year', 'Year')], default='Day', max_length=50),
        ),
    ]
