# Generated by Django 5.1.4 on 2024-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/ads/'),
        ),
        migrations.AlterField(
            model_name='medicaladvice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/advice/'),
        ),
    ]
