# Generated by Django 4.2.17 on 2025-01-06 09:20

import coms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0002_alter_ad_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='static/images/ads/default.png', upload_to='static/images/ads/', validators=[coms.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='medicaladvice',
            name='image',
            field=models.ImageField(default='static/images/advice/default.png', upload_to='static/images/advice/', validators=[coms.models.validate_image_file]),
        ),
    ]
