# Generated by Django 5.1.4 on 2024-12-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('coms', '0002_alter_ad_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
