# Generated by Django 5.1.3 on 2024-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='assigned_patients', through='accounts.DoctorPatient', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'administrator'), ('DOCTOR', 'doctor'), ('PATIENT', 'patient')], max_length=10),
        ),
    ]
