# Generated by Django 5.1.3 on 2024-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_patients_alter_userbase_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='assigned_patients', through='accounts.DoctorPatient', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='selected_doctors', through='accounts.DoctorPatient', to='accounts.patient'),
        ),
    ]
