# Generated by Django 4.2.17 on 2025-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userbase_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Dentist', 'Dentist'), ('Psychiatrist', 'Psychiatrist'), ('ENT', 'ENT'), ('Ripperdoc', 'Ripperdoc')], max_length=50),
        ),
    ]
